#
# TABLE STRUCTURE FOR: staff
# 300 people

DROP TABLE IF EXISTS `staff`;

CREATE TABLE `staff` (
  `staff_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `f_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `birthdate` date DEFAULT NULL,
  `birth_place` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `death_date` date DEFAULT NULL,
  `sex` char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`staff_id`)
) ENGINE=InnoDB AUTO_INCREMENT=301 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (1, 'Urban', 'Bruen', '1975-10-23', 'West Maribelberg', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (2, 'Garth', 'Moore', '1983-04-10', 'Dixieborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (3, 'Jeffry', 'Cummings', '2019-03-22', 'New Sheridanmouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (4, 'Jayce', 'Bayer', '2019-04-08', 'Prohaskamouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (5, 'Hardy', 'Jacobi', '2012-08-12', 'Ryanburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (6, 'Donnell', 'Hand', '1998-11-02', 'New Maverickland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (7, 'Albin', 'Anderson', '2018-06-08', 'Port Christaton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (8, 'Kaleigh', 'Spinka', '1998-03-13', 'O\'Connerton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (9, 'Kennith', 'Effertz', '1999-03-11', 'Schoenmouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (10, 'Chelsey', 'Goldner', '1992-04-03', 'Nameport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (11, 'Hailie', 'Batz', '1974-02-04', 'Kulasborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (12, 'Reymundo', 'Walter', '1972-07-26', 'Lake Kaciville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (13, 'Mackenzie', 'Hoeger', '1997-07-30', 'Lake Angiechester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (14, 'Raegan', 'Upton', '2006-03-29', 'West Edward', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (15, 'Lindsay', 'Reichel', '2007-10-25', 'Vinceton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (16, 'Angie', 'McDermott', '2015-07-27', 'Myrtleside', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (17, 'Kelton', 'Lang', '2006-08-14', 'New Rosendo', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (18, 'Delores', 'Beer', '2013-10-25', 'East Kaylinfort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (19, 'Emmy', 'Mosciski', '2019-01-04', 'New Timmothy', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (20, 'Hulda', 'Flatley', '2018-03-27', 'East Mosesfort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (21, 'Marielle', 'Botsford', '1985-01-31', 'Schummfurt', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (22, 'Camden', 'Konopelski', '1998-06-02', 'Brownhaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (23, 'Oceane', 'Heaney', '2019-12-17', 'Evangelineport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (24, 'Judson', 'Romaguera', '1976-06-18', 'Gleasonfurt', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (25, 'Jayden', 'Lowe', '2016-11-01', 'Ornstad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (26, 'Jerrod', 'Muller', '1992-12-10', 'South Garthton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (27, 'Vena', 'Altenwerth', '1973-01-02', 'East Torrance', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (28, 'Jayson', 'Jacobson', '1988-12-19', 'South Yvonne', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (29, 'Quinten', 'Kautzer', '2015-09-04', 'Port Eudoraview', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (30, 'Richard', 'Luettgen', '2015-02-22', 'Kossville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (31, 'Donny', 'Armstrong', '2018-07-12', 'West Houstonville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (32, 'Garrick', 'Schinner', '1970-01-05', 'New Misaelbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (33, 'Turner', 'Lubowitz', '2013-07-22', 'North Jazmyn', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (34, 'Hailee', 'Jast', '2019-09-01', 'Lake Laishaton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (35, 'Willard', 'Jacobi', '2007-05-11', 'Joseburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (36, 'Ashlynn', 'Anderson', '1992-06-17', 'East John', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (37, 'Angie', 'Collins', '2002-12-25', 'Dallinville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (38, 'Ludwig', 'Brown', '1994-11-01', 'Paigechester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (39, 'Armando', 'McKenzie', '2017-03-17', 'Vandervortfurt', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (40, 'Heber', 'Sauer', '1972-03-26', 'Schuppeside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (41, 'Michele', 'Kreiger', '1984-11-18', 'Kreigerton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (42, 'Grace', 'Zboncak', '1993-11-15', 'New Maude', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (43, 'Guillermo', 'Gottlieb', '2020-02-15', 'North Adolph', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (44, 'Sherman', 'Howe', '1970-06-05', 'Prosaccostad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (45, 'Lexie', 'Howe', '1996-08-31', 'Gloverborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (46, 'Isaias', 'Wiegand', '1999-09-05', 'Lake Vilma', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (47, 'Karlee', 'Berge', '2008-11-13', 'Littelshire', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (48, 'Ashley', 'Rutherford', '2002-03-04', 'Oberbrunnertown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (49, 'Emmet', 'Harber', '1980-05-31', 'North Johnbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (50, 'Lina', 'Kihn', '1999-06-01', 'East Bernice', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (51, 'Hermann', 'Bailey', '2012-10-20', 'Lake Emerson', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (52, 'Adriana', 'Wilkinson', '1992-12-24', 'New Anjali', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (53, 'Marilou', 'Smith', '2001-05-24', 'Gudrunchester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (54, 'Daron', 'Gerlach', '1990-12-27', 'New Waynetown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (55, 'Johnpaul', 'VonRueden', '1994-07-11', 'Howestad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (56, 'Krystal', 'Bernier', '1999-03-11', 'West Carolefurt', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (57, 'Nettie', 'Prosacco', '1975-02-10', 'Sadyehaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (58, 'Fae', 'Beahan', '2008-03-13', 'Port Margueritehaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (59, 'Kitty', 'Baumbach', '1998-12-22', 'Percyberg', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (60, 'Nickolas', 'Shields', '1991-02-13', 'Lake Jadynburgh', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (61, 'Kristin', 'Witting', '1981-03-23', 'East Vivianfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (62, 'Abner', 'Romaguera', '1978-12-13', 'West Bertahaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (63, 'Alexis', 'Wolff', '1992-11-12', 'West Brady', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (64, 'Nicola', 'Schmeler', '2010-03-14', 'Lake Rubiefurt', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (65, 'Greyson', 'Parker', '2016-04-26', 'Boyerborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (66, 'Mariah', 'Anderson', '2009-12-09', 'Melvinbury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (67, 'Ena', 'Rosenbaum', '1983-09-26', 'New Keely', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (68, 'Efrain', 'Herman', '1991-01-27', 'South Leilamouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (69, 'Josefina', 'Lubowitz', '2017-08-31', 'East Gustave', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (70, 'Johnathon', 'O\'Keefe', '2007-09-10', 'Reichelville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (71, 'Brown', 'Hessel', '2009-12-13', 'Christinabury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (72, 'Annetta', 'Hickle', '2015-05-24', 'Mandytown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (73, 'Pat', 'Gutkowski', '1987-11-13', 'Stiedemannfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (74, 'Hassie', 'Kuphal', '1996-01-28', 'East Harmon', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (75, 'Sienna', 'Ledner', '2013-09-05', 'East Winona', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (76, 'Doug', 'Casper', '2007-04-17', 'New Nakiatown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (77, 'Abraham', 'Paucek', '1999-05-01', 'South Hudsonside', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (78, 'Giovani', 'Kessler', '1986-11-10', 'Romainemouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (79, 'Bret', 'Kilback', '1993-07-01', 'Adrielfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (80, 'Sammy', 'Hirthe', '2014-02-22', 'Lake Vadaland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (81, 'Retta', 'McLaughlin', '1994-07-21', 'Keanuchester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (82, 'Connor', 'Rice', '2009-06-22', 'Ilatown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (83, 'Yasmine', 'Graham', '2013-06-10', 'Harberside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (84, 'Hazel', 'Ryan', '2017-08-06', 'Port Malika', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (85, 'Lysanne', 'Herman', '1988-02-28', 'Torphytown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (86, 'Helga', 'Pfannerstill', '1985-04-27', 'North Edythbury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (87, 'Braden', 'Lind', '1991-07-29', 'Siennaland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (88, 'Brown', 'Lynch', '2018-05-23', 'Streichmouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (89, 'Baron', 'Greenfelder', '1994-12-20', 'Port Albertha', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (90, 'Paris', 'Kessler', '1978-09-11', 'Magnusside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (91, 'Lavonne', 'Zieme', '2002-08-25', 'West Lauren', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (92, 'Destany', 'Heidenreich', '1992-10-06', 'South Tevin', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (93, 'Clotilde', 'Luettgen', '1976-12-04', 'Hodkiewicztown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (94, 'Nickolas', 'Stroman', '1991-09-27', 'Port Keeley', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (95, 'Vivien', 'Kiehn', '2000-01-14', 'East Serenityport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (96, 'Antone', 'Mayert', '1995-12-15', 'New Jordishire', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (97, 'Lorena', 'Friesen', '1998-09-07', 'Paoloburgh', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (98, 'Alysa', 'Gulgowski', '2004-04-09', 'Port Eloisa', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (99, 'Fiona', 'Kilback', '1995-11-11', 'Alexabury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (100, 'Aglae', 'Will', '1981-03-25', 'South Jonathan', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (101, 'Edd', 'Will', '1986-06-03', 'West Malachiborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (102, 'Harrison', 'Leuschke', '1993-09-03', 'Hilpertbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (103, 'Jonathan', 'Kuvalis', '2008-07-18', 'Cordellmouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (104, 'Roy', 'Emard', '1983-02-09', 'North Agnestown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (105, 'Amari', 'Lockman', '1982-01-03', 'Osinskiburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (106, 'Alex', 'Kassulke', '2019-10-25', 'Schusterchester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (107, 'Norris', 'Tromp', '1989-07-08', 'South Alexandrea', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (108, 'Dahlia', 'Feeney', '1973-04-29', 'Nellaland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (109, 'Diana', 'Glover', '1970-04-04', 'Lake Keon', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (110, 'Alda', 'Skiles', '2004-06-08', 'Yostport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (111, 'Carmela', 'Wilkinson', '1981-01-05', 'Denesikfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (112, 'Cassidy', 'Beier', '2013-12-09', 'Kertzmannville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (113, 'Cornelius', 'Graham', '1981-08-16', 'South Heatherburgh', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (114, 'Alicia', 'Nolan', '1990-11-20', 'Streichtown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (115, 'Name', 'Bailey', '2012-10-19', 'Rodriguezbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (116, 'Jaunita', 'Beier', '1985-01-31', 'North Leoniemouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (117, 'Stanton', 'Reinger', '1977-04-21', 'Raubury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (118, 'Drake', 'Turner', '1985-04-29', 'Mikelstad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (119, 'Kelly', 'Herzog', '1993-12-27', 'West Destinee', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (120, 'Richmond', 'Williamson', '1996-03-10', 'Greenholtfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (121, 'Augusta', 'Lehner', '1987-12-21', 'New Wyattstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (122, 'Serena', 'Lemke', '2004-01-21', 'Sauerfort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (123, 'Tierra', 'Schamberger', '2017-02-07', 'Sawaynshire', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (124, 'Elta', 'Smitham', '1982-05-25', 'North Letitia', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (125, 'Bessie', 'Wilderman', '1990-03-23', 'East Natalie', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (126, 'Emery', 'Luettgen', '2018-07-01', 'Adelbertland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (127, 'Chaya', 'Wiza', '2005-06-24', 'South Zena', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (128, 'Nat', 'Hickle', '2005-06-29', 'Osinskiborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (129, 'Alexandra', 'Halvorson', '2010-09-27', 'Weimannmouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (130, 'Lorenz', 'Pfannerstill', '1976-10-13', 'Thompsonton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (131, 'Julia', 'Graham', '1970-05-21', 'Blocktown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (132, 'Reagan', 'Donnelly', '2013-12-24', 'North Rowlandstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (133, 'Daisha', 'Robel', '1971-07-11', 'North Kian', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (134, 'Cynthia', 'Donnelly', '2014-11-04', 'West Juanita', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (135, 'Delilah', 'Simonis', '2010-06-29', 'South Abdullahland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (136, 'Josianne', 'Luettgen', '1973-11-29', 'Abbyport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (137, 'Elliott', 'Osinski', '1999-01-08', 'Turcottemouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (138, 'Jazlyn', 'Kertzmann', '2009-03-25', 'Port Antonetta', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (139, 'Lavonne', 'Heidenreich', '2011-07-07', 'Lake Casimirfort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (140, 'Marty', 'McLaughlin', '2005-04-04', 'Murphyville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (141, 'Lori', 'Rodriguez', '2009-03-19', 'Katlynnland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (142, 'Helmer', 'Welch', '2003-11-24', 'Alicechester', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (143, 'Neal', 'Collins', '1982-11-30', 'East Edison', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (144, 'Teagan', 'Fay', '1975-09-26', 'Alliebury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (145, 'Alia', 'Labadie', '1973-03-30', 'Schillerville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (146, 'Addie', 'Johnson', '1975-06-23', 'Lake Kaydentown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (147, 'Reynold', 'Von', '1976-04-17', 'Maggioport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (148, 'Stanford', 'Brown', '1983-05-11', 'Port Marta', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (149, 'Sylvia', 'Green', '2015-12-20', 'Whitefort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (150, 'Emerald', 'Hilpert', '1997-07-08', 'North Jonatanborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (151, 'Lorine', 'Gorczany', '2007-06-05', 'New Jamarville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (152, 'Domenic', 'Weimann', '2020-01-01', 'Thaliamouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (153, 'Herminio', 'Herman', '1999-05-09', 'Nitzscheview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (154, 'Breana', 'Kassulke', '1997-05-27', 'South Christian', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (155, 'Maci', 'White', '2009-04-04', 'Celineville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (156, 'Dewayne', 'Weimann', '1974-02-02', 'Marquiseberg', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (157, 'Tyrel', 'Bruen', '1972-02-21', 'East Santosborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (158, 'Abner', 'Gibson', '2017-08-21', 'Johnstonbury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (159, 'Vince', 'Fay', '1975-05-18', 'Langoshville', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (160, 'Darlene', 'Predovic', '2001-04-10', 'East Darianaport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (161, 'Palma', 'Hahn', '1992-10-21', 'South Monte', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (162, 'Felicity', 'Douglas', '1987-01-24', 'South Vada', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (163, 'Tanya', 'Berge', '1975-02-06', 'East Laurymouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (164, 'America', 'Boyle', '2020-01-24', 'East Sandra', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (165, 'Anabelle', 'Kautzer', '2016-04-09', 'North Willisport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (166, 'Deondre', 'Cruickshank', '2017-06-14', 'East Daren', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (167, 'Isabella', 'White', '2008-07-19', 'Wardhaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (168, 'Davon', 'Senger', '1985-06-10', 'Kemmerhaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (169, 'Jillian', 'Mitchell', '1992-08-08', 'Tillmanview', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (170, 'April', 'Bashirian', '1999-11-02', 'Groverview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (171, 'Felicity', 'Waelchi', '1989-12-10', 'New Ardithport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (172, 'Israel', 'Cartwright', '2005-10-22', 'North Jalen', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (173, 'Candida', 'Cremin', '1972-06-20', 'Anaside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (174, 'Lacy', 'Smitham', '1984-01-08', 'Jeraldland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (175, 'Carson', 'Beer', '1989-02-27', 'North Jadenborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (176, 'Lindsay', 'Pfannerstill', '1981-05-08', 'Lake Maynard', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (177, 'Pamela', 'Marvin', '1997-05-17', 'East Antoinetteview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (178, 'Hank', 'Ledner', '2012-10-13', 'South Alysson', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (179, 'Yasmin', 'Cronin', '1984-08-15', 'New Gaston', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (180, 'Sibyl', 'Flatley', '1997-05-10', 'Eloisamouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (181, 'Murl', 'Stokes', '1992-09-15', 'O\'Keefeborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (182, 'Bennett', 'Gaylord', '2013-10-12', 'Port Sanfordborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (183, 'Darryl', 'Erdman', '1989-02-28', 'Hilpertside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (184, 'Jeffry', 'King', '1999-04-29', 'Araside', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (185, 'Billy', 'Feest', '1998-02-17', 'Robertaport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (186, 'Tre', 'Gleason', '1983-06-19', 'North Madison', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (187, 'Jazmin', 'Kuphal', '1989-03-20', 'Port Arnaldo', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (188, 'Micheal', 'Emard', '1988-09-22', 'East Timmy', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (189, 'Selina', 'Bayer', '1990-11-23', 'Laurynshire', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (190, 'Frederic', 'Goyette', '2001-01-06', 'New Guy', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (191, 'Dwight', 'Bogisich', '1981-07-22', 'South Jamaalchester', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (192, 'Marlee', 'Kunze', '1987-06-24', 'Rolfsonfurt', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (193, 'Cruz', 'Lehner', '2014-02-22', 'East Gerhard', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (194, 'Pinkie', 'Kiehn', '2011-12-07', 'North Brodyland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (195, 'Norbert', 'Beier', '1980-08-07', 'Lake Ally', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (196, 'Reilly', 'Rippin', '2019-05-03', 'North Fabiola', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (197, 'Myron', 'Brakus', '1993-05-28', 'Gudrunfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (198, 'Kristy', 'Wisoky', '1976-05-11', 'Gerholdbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (199, 'Bessie', 'Swaniawski', '2012-07-05', 'McLaughlinland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (200, 'Afton', 'Hermann', '1976-09-25', 'Feltontown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (201, 'Keshawn', 'Ullrich', '2007-03-15', 'East Willowmouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (202, 'Sid', 'Collins', '1990-06-13', 'Thielstad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (203, 'Malika', 'Feeney', '1971-09-09', 'North Jessikamouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (204, 'Zetta', 'Emard', '2019-09-02', 'Treburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (205, 'Jettie', 'Robel', '1999-08-16', 'West Zackview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (206, 'Kristina', 'DuBuque', '2007-12-15', 'Goyettestad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (207, 'Jordi', 'Kuphal', '1992-01-21', 'Bartontown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (208, 'Glennie', 'Lueilwitz', '1980-05-23', 'Robynburgh', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (209, 'Bud', 'Klein', '2004-11-14', 'Tateton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (210, 'Sigurd', 'Kutch', '1998-02-18', 'Lake Maudhaven', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (211, 'Alexis', 'Mann', '1985-04-06', 'Port Madisen', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (212, 'Monique', 'Willms', '2003-07-09', 'Piercefurt', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (213, 'Nellie', 'Blick', '2009-12-06', 'Flatleyberg', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (214, 'Cecil', 'Kiehn', '2018-11-17', 'Ethelhaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (215, 'Shane', 'Waelchi', '1990-08-17', 'New Madaline', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (216, 'Jerrold', 'Cummerata', '1980-11-21', 'West Todbury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (217, 'Emilie', 'Gleichner', '1975-06-24', 'Horacetown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (218, 'Santina', 'Marks', '2004-01-21', 'West Monroe', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (219, 'Jordy', 'Graham', '2014-12-22', 'Kulasbury', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (220, 'Lilyan', 'Maggio', '2002-08-23', 'North Savanna', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (221, 'Keshawn', 'Lynch', '1987-08-06', 'West Tom', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (222, 'Larissa', 'Bins', '2014-09-11', 'North Jovany', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (223, 'Gilda', 'Willms', '1983-12-12', 'Port Ernestina', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (224, 'Merritt', 'Reilly', '1976-01-25', 'Matildaview', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (225, 'Grayson', 'Breitenberg', '2018-01-25', 'East Connor', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (226, 'Cristal', 'Rath', '2017-07-02', 'Ryanton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (227, 'Andrew', 'Schimmel', '1985-04-13', 'South Judgestad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (228, 'Anabel', 'Effertz', '1979-10-11', 'New Angelina', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (229, 'Tara', 'Gulgowski', '1982-08-03', 'New Margarita', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (230, 'Jazmin', 'Bins', '1983-01-15', 'Whitneyside', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (231, 'Eldon', 'Barrows', '1983-03-26', 'North Elyssa', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (232, 'Damon', 'Schulist', '1998-02-02', 'Port Thomas', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (233, 'Aditya', 'Zulauf', '1975-04-27', 'Port Natalia', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (234, 'Kris', 'Gaylord', '1982-12-02', 'Odieport', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (235, 'Providenci', 'Ruecker', '1990-10-28', 'New Shaunfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (236, 'Luisa', 'Treutel', '1974-12-12', 'Hillsstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (237, 'Kaleigh', 'Roberts', '2006-06-28', 'Tinaton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (238, 'Ariane', 'Swaniawski', '2019-06-03', 'Port Orland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (239, 'Liana', 'Nienow', '1972-11-18', 'West Tedstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (240, 'Mariane', 'Smitham', '1993-11-27', 'South Alainaborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (241, 'Beverly', 'Williamson', '2009-02-23', 'Dickinsonland', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (242, 'Roselyn', 'Leffler', '1984-05-21', 'Makennatown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (243, 'Elenora', 'Gleichner', '1975-08-31', 'Lefflerport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (244, 'Mac', 'Herzog', '2004-04-19', 'Salliemouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (245, 'Eldred', 'Keeling', '2002-02-19', 'North Ciara', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (246, 'Allene', 'Littel', '1975-04-08', 'West Camdenstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (247, 'Shayne', 'Flatley', '2019-04-03', 'Port Luigimouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (248, 'Dylan', 'Turcotte', '2001-10-16', 'Alvahaven', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (249, 'Melyna', 'Corwin', '1970-04-05', 'D\'Amoreborough', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (250, 'Spencer', 'Crist', '2006-06-13', 'Port Jaidenbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (251, 'Kavon', 'Kiehn', '1995-08-31', 'Jenkinsland', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (252, 'Trenton', 'Cummerata', '2016-08-08', 'East Elmoremouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (253, 'Tyree', 'Jones', '2014-07-01', 'Armanimouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (254, 'Tevin', 'Bayer', '2000-08-19', 'Brakusborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (255, 'Jacinto', 'Heller', '2013-04-05', 'Port Sarinamouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (256, 'Sylvan', 'Sawayn', '1976-08-15', 'Kallieburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (257, 'Sterling', 'Batz', '1974-06-10', 'East Jonatan', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (258, 'Isabelle', 'Bernier', '1989-03-27', 'Franeckiborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (259, 'Claud', 'Tremblay', '1988-05-08', 'Baumbachburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (260, 'Harmony', 'Friesen', '2016-12-08', 'South Delores', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (261, 'Emiliano', 'Reinger', '2009-12-27', 'Mrazview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (262, 'Delta', 'Shields', '1984-12-01', 'Wunschburgh', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (263, 'Josephine', 'Mertz', '1972-06-15', 'West Janessa', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (264, 'Brock', 'Stark', '1979-02-03', 'Lednershire', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (265, 'Arnold', 'Spencer', '2015-06-25', 'West Katelinborough', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (266, 'Laurine', 'Bruen', '1971-05-27', 'South Luisa', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (267, 'Zella', 'Sipes', '2017-08-12', 'Wunschstad', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (268, 'Abel', 'Gulgowski', '2002-01-28', 'Croninport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (269, 'Emily', 'Sanford', '2004-10-23', 'Hacketthaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (270, 'Kody', 'Leannon', '2001-11-10', 'Vladimirbury', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (271, 'Korey', 'Cormier', '1986-07-24', 'Lake Elinorechester', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (272, 'Loyce', 'Steuber', '1972-07-13', 'Reingerberg', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (273, 'Johann', 'Olson', '2001-05-30', 'Port Retachester', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (274, 'Gerson', 'Friesen', '2017-07-15', 'West Adrianafort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (275, 'Everette', 'Bernhard', '1975-01-19', 'West Omari', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (276, 'Sedrick', 'Raynor', '2012-12-18', 'O\'Reillyside', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (277, 'Kelli', 'Emmerich', '2019-03-20', 'South Aubrey', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (278, 'Ezekiel', 'Will', '1997-09-09', 'South Kristy', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (279, 'Domenica', 'Wolf', '1995-01-29', 'North Robertmouth', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (280, 'Lavon', 'Dickens', '1988-05-14', 'Port Dorothytown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (281, 'Reggie', 'Corwin', '1973-05-07', 'Torpview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (282, 'Chesley', 'Volkman', '2014-08-08', 'Greenhaven', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (283, 'Nettie', 'Lakin', '1981-02-11', 'Medhurstport', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (284, 'Gilberto', 'Pfannerstill', '1976-08-23', 'Wendellville', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (285, 'Martin', 'Farrell', '2015-01-07', 'Tremblayton', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (286, 'Giles', 'McKenzie', '2014-11-23', 'North Pierremouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (287, 'Percival', 'Pollich', '1983-06-29', 'Walterfort', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (288, 'Allie', 'Beier', '2002-06-09', 'Lake Evanhaven', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (289, 'Gail', 'Nitzsche', '1970-10-02', 'Roweton', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (290, 'Guy', 'Casper', '1989-03-28', 'North Princestad', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (291, 'Zita', 'Larkin', '1983-11-16', 'East Samshire', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (292, 'Robb', 'Collins', '2011-06-24', 'North Jermainemouth', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (293, 'Ada', 'Wuckert', '1998-05-06', 'Aishaview', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (294, 'Isaac', 'VonRueden', '1991-04-02', 'East Elenor', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (295, 'Hattie', 'Jacobson', '1990-09-26', 'North Tierratown', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (296, 'Irwin', 'Wuckert', '1990-10-15', 'East Werner', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (297, 'Durward', 'Conn', '1973-04-15', 'Daphneefurt', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (298, 'Magali', 'Krajcik', '1979-07-20', 'Jacobsonfort', NULL, 'm');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (299, 'Rocky', 'Hackett', '2014-11-12', 'Hickletown', NULL, 'f');
INSERT INTO `staff` (`staff_id`, `name`, `f_name`, `birthdate`, `birth_place`, `death_date`, `sex`) VALUES (300, 'Haskell', 'Smith', '2014-06-17', 'O\'Keefeborough', NULL, 'f');


